package br.com.dominio.desafioatech.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.hibernate.validator.constraints.Length;

@DynamoDBDocument
@ToString
@EqualsAndHashCode
@Getter
@Setter
@DynamoDBTable(tableName = "Usuario")
public class DesafioModel {

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "nome")
    private String nome;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBDelimited(delimiter = 6, attributeNames = {"AttSenha"})
    @DynamoDBAttribute(attributeName = "senha")
    private String senha;

    @DynamoDBAttribute(attributeName = "itemApagado")
    private String itemApagado;

    @DynamoDBAttribute(attributeName = "nomeUsuario")
    private String nomeUsuario;
    public DesafioModel(String nome, String email, String senha, String itemApagado, String nomeUsuario){
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.itemApagado = itemApagado;
        this.nomeUsuario = nomeUsuario;
    }

}
